### ISSUE TITLE
AWS EMR: ImportError: cannot import name ReadTimeoutError

### ISSUE THREAD

**Issue by unkrich** [commoncrawl/cc-mrjob#26]
Putting this here in case someone runs into the same issue running jobs on AWS EMR. 

When running the standard example tag_counter_emr.py on AWS EMR, I experienced an error "ImportError: cannot import name ReadTimeoutError". 

After some research, I found that this had something to do with the version of boto3/botocore that is installed during bootstrapping. I was able to resolve it by specifying versions in the mrjob.conf file under bootstrapping, specifically what worked for me was 

`botocore==1.12.91
urllib3==1.24.1
boto3==1.9.91`

**Comment by sebastian-nagel** [comment]
Hi @unkrich, thanks for the notice!
