### ISSUE TITLE
Error Launching job : Output directory s3://mapreducecommoncrawl/output1 already exists. Streaming Command Failed! Command exiting with ret '5'

### ISSUE THREAD

**Issue by PhuongDelrosario** [commoncrawl/cc-mrjob#28]
Firstly, thank you very much for sharing.  I am learning and i have been trying this for 3 days now. 
I encountered several problems about setup but i was able to fix it.  However, this problem: the "s3://mapreducecommoncrawl/output1" folder was not exist before running the job.

I only created the bucket named "mapreducecommoncrawl" and I created input folder and script folder. I uploaded the "test-100.wet" to the input folder and word_count_emr.py to the script folder only. 
I have free tier aws account. I setup EC2_key and path, and everything... 

mrjob.conf
  # AWS region
    #  - recommended region: us-east-1 (where Common Crawl data lives)
    #  - if us-east-1 is used must also specify a bucket (cloud_tmp_dir)
    #    used to keep job data (must be also in the us-east-1 region)
    region: us-east-1
    cloud_tmp_dir: s3://mapreducecommoncrawl/output1/ 
    # could also specify the availability zone
    #zone: us-east-1c
 # Either set the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    # or set the two variables below
    aws_access_key_id: AKIA-------- (# i did put my full key here)
    aws_secret_access_key: tD7dlX------(# i did put my full secret key here)
    # For more control over ssh, it's highly recommended to add your key pair
    ec2_key_pair: EMR
    ec2_key_pair_file: C:/Users/truon/Documents/commoncarwl/mrjob/cc-mrjob-master/ssh/EMR.pem
    ssh_tunnel: true
    #ssh_tunnel_to_job_tracker: true

this is the error: 
syslog:
2021-01-29 03:22:50,997 INFO org.apache.hadoop.yarn.client.RMProxy (main): Connecting to ResourceManager at ip-172-31-46-55.ec2.internal/172.31.46.55:8032
2021-01-29 03:22:51,200 INFO org.apache.hadoop.yarn.client.AHSProxy (main): Connecting to Application History server at ip-172-31-46-55.ec2.internal/172.31.46.55:10200
2021-01-29 03:22:51,242 INFO org.apache.hadoop.yarn.client.RMProxy (main): Connecting to ResourceManager at ip-172-31-46-55.ec2.internal/172.31.46.55:8032
2021-01-29 03:22:51,242 INFO org.apache.hadoop.yarn.client.AHSProxy (main): Connecting to Application History server at ip-172-31-46-55.ec2.internal/172.31.46.55:10200
2021-01-29 03:22:51,432 ERROR org.apache.hadoop.streaming.StreamJob (main): Error Launching job : Output directory s3://mapreducecommoncrawl/output1 already exists

stderr:
Streaming Command Failed!
Command exiting with ret '5'

e updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be found here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
  warnings.warn(warning, PythonDeprecationWarning)
Creating temp directory c:\users\truon\appdata\local\temp\word_count_emr.truon.20210129.031650.389000
writing master bootstrap script to c:\users\truon\appdata\local\temp\word_count_emr.truon.20210129.031650.389000\b.sh
uploading working dir files to s3://mapreducecommoncrawl/output1/word_count_emr.truon.20210129.031650.389000/files/wd...
Copying other local files to s3://mapreducecommoncrawl/output1/word_count_emr.truon.20210129.031650.389000/files/
Created new cluster j-2Q67IJKJTJXVR
Added EMR tags to cluster j-2Q67IJKJTJXVR: __mrjob_label=word_count_emr, __mrjob_owner=truon, __mrjob_version=0.7.4
Waiting for Step 1 of 1 (s-22RE9U4XNIIGM) to complete...
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is STARTING)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  PENDING (cluster is BOOTSTRAPPING: Running bootstrap actions)
  master node is ec2-54-86-31-210.compute-1.amazonaws.com
  Connect to resource manager at: http://localhost:40389/cluster
  PENDING (cluster is RUNNING: Running step)
  FAILED
Cluster j-2Q67IJKJTJXVR is RUNNING: Running step
Attempting to fetch counters from logs...
Looking for step log in /mnt/var/log/hadoop/steps/s-22RE9U4XNIIGM on ec2-54-86-31-210.compute-1.amazonaws.com...
  Parsing step log: ssh://ec2-54-86-31-210.compute-1.amazonaws.com/mnt/var/log/hadoop/steps/s-22RE9U4XNIIGM/syslog
Looking for step log in /mnt/var/log/hadoop/steps/s-22RE9U4XNIIGM on ec2-54-86-31-210.compute-1.amazonaws.com...
  Parsing step log: ssh://ec2-54-86-31-210.compute-1.amazonaws.com/mnt/var/log/hadoop/steps/s-22RE9U4XNIIGM/stderr
Can't fetch history log; missing job ID
No counters found
Scanning logs for probable cause of failure...
Can't fetch history log; missing job ID
Can't fetch task logs; missing application ID

Probable cause of failure:

Streaming Command Failed!
Command exiting with ret '5'

**Comment by sebastian-nagel** [comment]
Hi @PhuongDelrosario, are you sure that the error message
```
2021-01-29 03:22:51,432 ERROR org.apache.hadoop.streaming.StreamJob (main): Error Launching job : Output directory s3://mapreducecommoncrawl/output1 already exists
```
is erroneous? One of the first steps of a MapReduce job is to verify that the output folder does not exist to avoid that data is overwritten and that there are no concurrent jobs writing into the same directory. Also note that a previous job, also a failed one, may have created the output directory. Using the [AWS CLI](https://aws.amazon.com/cli/) is the easiest way to verify whether the output directory exists:
```
aws s3 ls s3://mapreducecommoncrawl/output1/
```
Alternatively, you could log in into the EMR master node and run
```
hadoop fs -ls s3://mapreducecommoncrawl/output1/
```

One final remark: the project [cc-pyspark ](//github.com/commoncrawl/cc-pyspark) is a modern replacement for cc-mrjob. It's based on Apache Spark and Python 3. It can also be used on AWS EMR.

**Comment by sebastian-nagel** [comment]
One point: the line `cloud_tmp_dir: s3://mapreducecommoncrawl/output1/` defines `output1/` also as temp folder. This path must be different from the output directory passed as argument when launching the job. Sorry, just discovered this while scrolling once again through the issue.

**Comment by PhuongDelrosario** [comment]
Thank you very much for your quick reply. 
To make sure I understand it right. 
The cloud_tmp_dir path must be different from the directory output path, but  They can be in the same bucket right? 
Thanks  again

**Comment by sebastian-nagel** [comment]
> The cloud_tmp_dir path must be different from the directory output path, but They can be in the same bucket right?

Yes.
